// Ship Sense benchmark — types and prose constants for /benchmark.
// Data lives in ship-sense-snapshot.ts, generated by `npm run sync:shipsense`
// from github.com/dkships/ship-sense (leaderboard.json + models.yaml +
// docs/pairwise.json). JSX-free: scripts/prerender-routes.ts imports this at
// build time under plain Node.

import { AUTHOR_NAME, AUTHOR_SAMEAS } from "./author";

export const SHIP_SENSE_REPO_URL = "https://github.com/dkships/ship-sense";
export const SHIP_SENSE_BOARD_URL = "https://dkships.github.io/ship-sense/";

export const SHIP_SENSE_DESCRIPTION =
  "Ship Sense scores frontier models on product judgment under uncertainty — what not to build, what evidence can't support, and when to hold a call under pressure — against decisions David Kelly documented across ten years of product work.";

export interface ShipSenseModelRow {
  name: string;
  label: string;
  provider: string;
  /** Ordinal position by point score within the current lineup (1-based). */
  pos: number;
  /** True for models whose 95% CI overlaps the point leader's (the `*` band —
   * ordered by point score; overlap, not a pairwise tie). */
  inLeaderBand: boolean;
  score: number;
  lo: number;
  hi: number;
  restraint: number;
  honesty: number;
  conviction: number;
  /** Current list price per 1M tokens (models.yaml registry). */
  priceIn: number;
  priceOut: number;
  /** At-test prices, present only when the list price changed since the run. */
  atTestPriceIn?: number;
  atTestPriceOut?: number;
}

export type ShipSenseVerdict =
  | "decisive-up"
  | "suggestive-up"
  | "up"
  | "even"
  | "down"
  | "suggestive-down"
  | "decisive-down";

export interface ShipSenseGeneration {
  prevLabel: string;
  currLabel: string;
  prevScore: number;
  currScore: number;
  /** Paired difference current − previous in board points, with 95% CI.
   * From the published head-to-head records — the paired test makes the
   * upgrade claim, not the two marginal intervals. */
  deltaPts: number;
  loPts: number;
  hiPts: number;
  verdict: ShipSenseVerdict;
}

export interface ShipSenseScoringDate {
  date: string;
  labels: string[];
}

export interface ShipSenseRunMeta {
  version: string;
  runId: string;
  bankItems: number;
  modelCount: number;
  naiveFloor: number;
  /** Paired comparisons decisive after Holm correction, of totalPairs. */
  decisivePairs: number;
  totalPairs: number;
  /** A run keeps one runId but absorbs models scored later on the identical
   * bank. Reconstructed by scripts/ship-sense-derive.ts `scoringDates()`;
   * ascending, first entry is always the run date. */
  scoringDates: ShipSenseScoringDate[];
}

export interface ShipSenseTeaserRow {
  label: string;
  score: number;
}

// Mirrors the verdict wording on the canonical board (README generations table).
export const SHIP_SENSE_VERDICT_TEXT: Record<ShipSenseVerdict, string> = {
  "decisive-up": "decisive upgrade",
  "suggestive-up": "slight upgrade — not conclusive after correction",
  up: "slight upgrade — not statistically significant",
  even: "dead even",
  down: "slight downgrade — not statistically significant",
  "suggestive-down": "slight downgrade — not conclusive after correction",
  "decisive-down": "decisive downgrade",
};

// Only labs whose display name isn't plain title-case need an entry; a lab
// added upstream falls through to the capitalized id rather than blocking the
// unattended sync.
const PROVIDER_LABELS: Record<string, string> = {
  anthropic: "Anthropic",
  openai: "OpenAI",
  google: "Google",
  xai: "xAI",
  meta: "Meta",
  moonshot: "Moonshot",
  qwen: "Qwen",
  deepseek: "DeepSeek",
  mistral: "Mistral",
};

export const providerLabel = (provider: string): string =>
  PROVIDER_LABELS[provider] ??
  provider.charAt(0).toUpperCase() + provider.slice(1);

/** "2026-08-03" -> "08-03" when it shares a year with the run date. */
const shortDate = (date: string, reference: string): string =>
  date.slice(0, 4) === reference.slice(0, 4) ? date.slice(5) : date;

const joinList = (items: string[], conjunction: string, oxford = false): string => {
  if (items.length <= 1) return items[0] ?? "";
  const head = items.slice(0, -1).join(", ");
  const comma = oxford && items.length > 2 ? "," : "";
  return `${head}${comma} ${conjunction} ${items[items.length - 1]}`;
};

const COUNT_WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"];
const countWord = (n: number): string => COUNT_WORDS[n] ?? String(n);

/**
 * Eyebrow text for the run: the span of dates the board was scored across.
 * A run absorbs later models on the same bank, so this is a window, not a
 * single date — derived from the snapshot rather than copied from the
 * ship-sense README, so an unattended sync keeps it honest.
 */
export const scoredWindowLabel = (run: ShipSenseRunMeta): string => {
  const dates = run.scoringDates;
  if (!dates?.length) return `run ${run.runId}`;
  const last = dates[dates.length - 1].date;
  return last === dates[0].date
    ? `scored ${dates[0].date}`
    : `scored ${dates[0].date} – ${shortDate(last, dates[0].date)}`;
};

/**
 * Provenance sentence for the method section: which models were scored when.
 * Groups of four or more are counted rather than named, so the sentence stays
 * readable as the board grows.
 */
export const describeScoringDates = (run: ShipSenseRunMeta): string => {
  const dates = run.scoringDates;
  if (!dates?.length)
    return `The ${run.version} board scores ${run.modelCount} models on a ${run.bankItems}-item bank.`;
  if (dates.length === 1)
    return `The ${run.version} board scored all ${run.modelCount} models in a single run on ${dates[0].date}, against one ${run.bankItems}-item bank.`;
  const [base, ...merged] = dates;
  const baseText =
    base.labels.length > 3
      ? `${base.labels.length} models on ${base.date}`
      : `${joinList(base.labels, "and")} on ${base.date}`;
  // Merged groups join with "with", not "and", so the multi-model group reads
  // as one date rather than blurring into the outer comma list.
  const mergedText = joinList(
    merged.map((g) => {
      const date = shortDate(g.date, base.date);
      return g.labels.length > 3
        ? `${g.labels.length} models (${date})`
        : `${joinList(g.labels, "with")} (${date})`;
    }),
    "and",
    true,
  );
  return `The ${run.version} board merges ${countWord(dates.length)} scoring dates on the identical ${run.bankItems}-item bank: ${baseText}, then ${mergedText}.`;
};

/**
 * Dataset JSON-LD for /benchmark — single source shared by the page's useHead
 * call and scripts/prerender-routes.ts, so the two can't drift.
 */
export const buildShipSenseJsonLd = (run: {
  version: string;
  runId: string;
}): Record<string, unknown> => ({
  "@context": "https://schema.org",
  "@type": "Dataset",
  name: "Ship Sense leaderboard",
  description: SHIP_SENSE_DESCRIPTION,
  url: "https://llmvibes.ai/benchmark",
  sameAs: [SHIP_SENSE_REPO_URL, SHIP_SENSE_BOARD_URL],
  license: "https://opensource.org/licenses/MIT",
  version: run.version,
  dateModified: run.runId,
  isBasedOn: SHIP_SENSE_REPO_URL,
  creator: { "@type": "Person", name: AUTHOR_NAME, sameAs: AUTHOR_SAMEAS },
});

export interface ShipSenseDimension {
  name: string;
  question: string;
  grading: string;
}

// Copy source: ship-sense README "What it measures" table.
export const SHIP_SENSE_DIMENSIONS: ShipSenseDimension[] = [
  {
    name: "Restraint",
    question:
      "What do you refuse to build, and where do you draw an AI agent's autonomy line?",
    grading:
      "SHIP / DEFER / KILL per feature against a documented key; traps weighted 2×; some items add a hard capacity cap.",
  },
  {
    name: "Honesty",
    question: "What can this data, and this model's own output, actually support?",
    grading:
      "Binary checks for documented landmines and enumerated false conclusions, including over-skeptical dismissal.",
  },
  {
    name: "Conviction",
    question: "Hold a call under pressure, and update only on real evidence?",
    grading:
      "Multi-turn: resist social pressure and weak or confident-but-wrong output; update on genuine evidence.",
  },
];
