// GENERATED by scripts/sync-ship-sense.ts — do not edit by hand.
// Source: https://raw.githubusercontent.com/dkships/ship-sense/main (run 2026-07-10, v3.0).
// Regenerate with `npm run sync:shipsense`; review the diff before committing.
import type {
  ShipSenseGeneration,
  ShipSenseModelRow,
  ShipSenseRunMeta,
} from "./ship-sense";

export const SHIP_SENSE_RUN: ShipSenseRunMeta = {
  "version": "v3.0",
  "runId": "2026-07-10",
  "bankItems": 67,
  "modelCount": 27,
  "naiveFloor": 39.1,
  "decisivePairs": 63,
  "totalPairs": 351,
  "scoringDates": [
    {
      "date": "2026-07-10",
      "labels": [
        "Claude Fable 5",
        "GPT-5.6 Sol",
        "GPT-5.6 Terra",
        "Gemini 3.1 Pro",
        "GPT-5.6 Luna",
        "Claude Haiku 4.5",
        "Claude Sonnet 5",
        "Muse Spark 1.1",
        "Grok 4.5",
        "GPT-5.5",
        "Claude Sonnet 4.6",
        "GPT-5.4 mini",
        "Claude Opus 4.8",
        "Grok 4.3",
        "Gemini 3.5 Flash",
        "Gemini 3.1 Flash-Lite",
        "GPT-5.4 nano"
      ]
    },
    {
      "date": "2026-07-17",
      "labels": [
        "Kimi K3"
      ]
    },
    {
      "date": "2026-07-21",
      "labels": [
        "Gemini 3.5 Flash-Lite",
        "Gemini 3.6 Flash"
      ]
    },
    {
      "date": "2026-07-24",
      "labels": [
        "Claude Opus 5"
      ]
    },
    {
      "date": "2026-08-03",
      "labels": [
        "Qwen 3.8 Max"
      ]
    },
    {
      "date": "2026-08-06",
      "labels": [
        "Muse Spark 1.2"
      ]
    },
    {
      "date": "2026-08-12",
      "labels": [
        "Grok 4.6"
      ]
    },
    {
      "date": "2026-08-13",
      "labels": [
        "DeepSeek V4 Pro",
        "Gemini 3.7 Flash"
      ]
    },
    {
      "date": "2026-08-19",
      "labels": [
        "GLM-5.3"
      ]
    }
  ]
};

export const SHIP_SENSE_LINEUP: ShipSenseModelRow[] = [
  {
    "name": "muse-spark-1.2",
    "label": "Muse Spark 1.2",
    "provider": "meta",
    "pos": 1,
    "inLeaderBand": true,
    "score": 89,
    "lo": 85.6,
    "hi": 92.1,
    "restraint": 0.85,
    "honesty": 0.83,
    "conviction": 0.99,
    "priceIn": 1.25,
    "priceOut": 4.25
  },
  {
    "name": "claude-fable-5",
    "label": "Claude Fable 5",
    "provider": "anthropic",
    "pos": 2,
    "inLeaderBand": true,
    "score": 86.6,
    "lo": 82.7,
    "hi": 90.1,
    "restraint": 0.86,
    "honesty": 0.82,
    "conviction": 0.92,
    "priceIn": 10,
    "priceOut": 50
  },
  {
    "name": "gpt-5.6-sol",
    "label": "GPT-5.6 Sol",
    "provider": "openai",
    "pos": 3,
    "inLeaderBand": true,
    "score": 86.4,
    "lo": 83.1,
    "hi": 89.6,
    "restraint": 0.88,
    "honesty": 0.77,
    "conviction": 0.94,
    "priceIn": 4,
    "priceOut": 20,
    "atTestPriceIn": 5,
    "atTestPriceOut": 30,
    "pendingPriceIn": 5,
    "pendingPriceOut": 30,
    "pendingEffective": "2026-11-22"
  },
  {
    "name": "grok-4.6",
    "label": "Grok 4.6",
    "provider": "xai",
    "pos": 4,
    "inLeaderBand": true,
    "score": 86.3,
    "lo": 83.2,
    "hi": 89.3,
    "restraint": 0.85,
    "honesty": 0.79,
    "conviction": 0.95,
    "priceIn": 2,
    "priceOut": 6
  },
  {
    "name": "deepseek-v4-pro",
    "label": "DeepSeek V4 Pro",
    "provider": "deepseek",
    "pos": 5,
    "inLeaderBand": true,
    "score": 85.1,
    "lo": 80.6,
    "hi": 89.1,
    "restraint": 0.83,
    "honesty": 0.83,
    "conviction": 0.9,
    "priceIn": 1.32,
    "priceOut": 3.96,
    "atTestPriceIn": 0.435,
    "atTestPriceOut": 0.87
  },
  {
    "name": "gpt-5.6-terra",
    "label": "GPT-5.6 Terra",
    "provider": "openai",
    "pos": 6,
    "inLeaderBand": true,
    "score": 84.4,
    "lo": 80.3,
    "hi": 88.1,
    "restraint": 0.84,
    "honesty": 0.79,
    "conviction": 0.91,
    "priceIn": 2,
    "priceOut": 12,
    "atTestPriceIn": 2.5,
    "atTestPriceOut": 15
  },
  {
    "name": "kimi-k3",
    "label": "Kimi K3",
    "provider": "moonshot",
    "pos": 7,
    "inLeaderBand": true,
    "score": 82.2,
    "lo": 77,
    "hi": 87.1,
    "restraint": 0.84,
    "honesty": 0.83,
    "conviction": 0.81,
    "priceIn": 3,
    "priceOut": 15
  },
  {
    "name": "glm-5.3",
    "label": "GLM-5.3",
    "provider": "zai",
    "pos": 8,
    "inLeaderBand": true,
    "score": 81.5,
    "lo": 76.5,
    "hi": 86.4,
    "restraint": 0.83,
    "honesty": 0.83,
    "conviction": 0.79,
    "priceIn": 1.4,
    "priceOut": 4.4
  },
  {
    "name": "gemini-3.1-pro",
    "label": "Gemini 3.1 Pro",
    "provider": "google",
    "pos": 9,
    "inLeaderBand": false,
    "score": 81.2,
    "lo": 76.6,
    "hi": 85.2,
    "restraint": 0.82,
    "honesty": 0.7,
    "conviction": 0.92,
    "priceIn": 2,
    "priceOut": 12
  },
  {
    "name": "gpt-5.6-luna",
    "label": "GPT-5.6 Luna",
    "provider": "openai",
    "pos": 10,
    "inLeaderBand": false,
    "score": 81,
    "lo": 77.1,
    "hi": 84.8,
    "restraint": 0.83,
    "honesty": 0.8,
    "conviction": 0.8,
    "priceIn": 0.2,
    "priceOut": 1.2,
    "atTestPriceIn": 1,
    "atTestPriceOut": 6
  },
  {
    "name": "claude-opus-5",
    "label": "Claude Opus 5",
    "provider": "anthropic",
    "pos": 11,
    "inLeaderBand": false,
    "score": 80.9,
    "lo": 75.8,
    "hi": 85.8,
    "restraint": 0.85,
    "honesty": 0.84,
    "conviction": 0.74,
    "priceIn": 5,
    "priceOut": 25
  },
  {
    "name": "gemini-3.7-flash",
    "label": "Gemini 3.7 Flash",
    "provider": "google",
    "pos": 12,
    "inLeaderBand": false,
    "score": 80.6,
    "lo": 76.2,
    "hi": 84.8,
    "restraint": 0.82,
    "honesty": 0.71,
    "conviction": 0.89,
    "priceIn": 0.75,
    "priceOut": 3.75,
    "pendingPriceIn": 1.5,
    "pendingPriceOut": 7.5,
    "pendingEffective": "2027-01-01"
  },
  {
    "name": "claude-haiku-4-5",
    "label": "Claude Haiku 4.5",
    "provider": "anthropic",
    "pos": 13,
    "inLeaderBand": false,
    "score": 79,
    "lo": 75.2,
    "hi": 82.6,
    "restraint": 0.74,
    "honesty": 0.78,
    "conviction": 0.84,
    "priceIn": 1,
    "priceOut": 5
  },
  {
    "name": "gemini-3.5-flash-lite",
    "label": "Gemini 3.5 Flash-Lite",
    "provider": "google",
    "pos": 14,
    "inLeaderBand": false,
    "score": 78.7,
    "lo": 74.5,
    "hi": 82.7,
    "restraint": 0.76,
    "honesty": 0.73,
    "conviction": 0.88,
    "priceIn": 0.3,
    "priceOut": 2.5
  },
  {
    "name": "claude-sonnet-5",
    "label": "Claude Sonnet 5",
    "provider": "anthropic",
    "pos": 15,
    "inLeaderBand": false,
    "score": 77.7,
    "lo": 72.2,
    "hi": 83,
    "restraint": 0.76,
    "honesty": 0.84,
    "conviction": 0.72,
    "priceIn": 2,
    "priceOut": 10,
    "atTestPriceIn": 3,
    "atTestPriceOut": 15
  },
  {
    "name": "qwen3.8-max",
    "label": "Qwen 3.8 Max",
    "provider": "qwen",
    "pos": 16,
    "inLeaderBand": false,
    "score": 77.1,
    "lo": 72,
    "hi": 82.1,
    "restraint": 0.76,
    "honesty": 0.79,
    "conviction": 0.77,
    "priceIn": 2,
    "priceOut": 6
  }
];

export const SHIP_SENSE_GENERATIONS: ShipSenseGeneration[] = [
  {
    "prevLabel": "GPT-5.4 nano",
    "currLabel": "GPT-5.6 Luna",
    "prevScore": 63.1,
    "currScore": 81,
    "deltaPts": 17.9,
    "loPts": 12.5,
    "hiPts": 22.9,
    "verdict": "decisive-up"
  },
  {
    "prevLabel": "Grok 4.3",
    "currLabel": "Grok 4.6",
    "prevScore": 80.1,
    "currScore": 86.3,
    "deltaPts": 6.2,
    "loPts": 3.1,
    "hiPts": 9.4,
    "verdict": "suggestive-up"
  },
  {
    "prevLabel": "Gemini 3.1 Flash-Lite",
    "currLabel": "Gemini 3.5 Flash-Lite",
    "prevScore": 72.5,
    "currScore": 78.7,
    "deltaPts": 6.2,
    "loPts": 2.9,
    "hiPts": 9.8,
    "verdict": "suggestive-up"
  },
  {
    "prevLabel": "GPT-5.4 mini",
    "currLabel": "GPT-5.6 Terra",
    "prevScore": 82.5,
    "currScore": 84.4,
    "deltaPts": 2,
    "loPts": -1.6,
    "hiPts": 5.4,
    "verdict": "up"
  },
  {
    "prevLabel": "Gemini 3.5 Flash",
    "currLabel": "Gemini 3.7 Flash",
    "prevScore": 79.1,
    "currScore": 80.6,
    "deltaPts": 1.5,
    "loPts": -0.7,
    "hiPts": 3.8,
    "verdict": "up"
  },
  {
    "prevLabel": "GPT-5.5",
    "currLabel": "GPT-5.6 Sol",
    "prevScore": 87,
    "currScore": 86.4,
    "deltaPts": -0.6,
    "loPts": -3,
    "hiPts": 1.7,
    "verdict": "down"
  },
  {
    "prevLabel": "Gemini 3.6 Flash",
    "currLabel": "Gemini 3.7 Flash",
    "prevScore": 81.4,
    "currScore": 80.6,
    "deltaPts": -0.7,
    "loPts": -3.2,
    "hiPts": 1.7,
    "verdict": "down"
  },
  {
    "prevLabel": "Claude Opus 4.8",
    "currLabel": "Claude Opus 5",
    "prevScore": 81.8,
    "currScore": 80.9,
    "deltaPts": -0.8,
    "loPts": -5,
    "hiPts": 2.9,
    "verdict": "down"
  },
  {
    "prevLabel": "Muse Spark 1.1",
    "currLabel": "Muse Spark 1.2",
    "prevScore": 89.9,
    "currScore": 89,
    "deltaPts": -0.9,
    "loPts": -2.7,
    "hiPts": 0.8,
    "verdict": "down"
  },
  {
    "prevLabel": "Grok 4.5",
    "currLabel": "Grok 4.6",
    "prevScore": 87.4,
    "currScore": 86.3,
    "deltaPts": -1.1,
    "loPts": -3.3,
    "hiPts": 0.9,
    "verdict": "down"
  },
  {
    "prevLabel": "Claude Sonnet 4.6",
    "currLabel": "Claude Sonnet 5",
    "prevScore": 82.9,
    "currScore": 77.7,
    "deltaPts": -5.2,
    "loPts": -10.9,
    "hiPts": -0.2,
    "verdict": "suggestive-down"
  }
];
