// Ship Sense benchmark — types and prose constants for /benchmark.
// Data lives in ship-sense-snapshot.ts, generated by `npm run sync:shipsense`
// from github.com/dkships/ship-sense (leaderboard.json + models.yaml +
// docs/pairwise.json). JSX-free: scripts/prerender-routes.ts imports this at
// build time under plain Node.

import { AUTHOR_NAME, AUTHOR_SAMEAS } from "./author";

export const SHIP_SENSE_REPO_URL = "https://github.com/dkships/ship-sense";
export const SHIP_SENSE_BOARD_URL = "https://dkships.github.io/ship-sense/";

export const SHIP_SENSE_DESCRIPTION =
  "Ship Sense scores frontier models on product judgment under uncertainty — what not to build, what evidence can't support, and when to hold a call under pressure — against decisions David Kelly documented across ten years of product work.";

// The v3.0 board was merged across four scoring dates (17 models on the run
// date, then Kimi K3 07-17, Gemini 3.6 Flash + 3.5 Flash-Lite 07-21, Claude
// Opus 5 07-24 — ship-sense README "What it found"). The window exists only in
// prose, not in leaderboard.json, so it's keyed by runId here: update this map
// deliberately with each sync. Missing runId falls back to "Run <runId>".
export const SHIP_SENSE_SCORED_WINDOW: Record<string, string> = {
  "2026-07-10": "scored 2026-07-10 – 07-24",
};

export interface ShipSenseModelRow {
  name: string;
  label: string;
  provider: string;
  /** Ordinal position by point score within the current lineup (1-based). */
  pos: number;
  /** True for models whose 95% CI overlaps the point leader's (the `*` band —
   * ordered by point score; overlap, not a pairwise tie). */
  inLeaderBand: boolean;
  score: number;
  lo: number;
  hi: number;
  restraint: number;
  honesty: number;
  conviction: number;
  /** Current list price per 1M tokens (models.yaml registry). */
  priceIn: number;
  priceOut: number;
  /** At-test prices, present only when the list price changed since the run. */
  atTestPriceIn?: number;
  atTestPriceOut?: number;
}

export type ShipSenseVerdict =
  | "decisive-up"
  | "suggestive-up"
  | "up"
  | "even"
  | "down"
  | "suggestive-down"
  | "decisive-down";

export interface ShipSenseGeneration {
  prevLabel: string;
  currLabel: string;
  prevScore: number;
  currScore: number;
  /** Paired difference current − previous in board points, with 95% CI.
   * From the published head-to-head records — the paired test makes the
   * upgrade claim, not the two marginal intervals. */
  deltaPts: number;
  loPts: number;
  hiPts: number;
  verdict: ShipSenseVerdict;
}

export interface ShipSenseRunMeta {
  version: string;
  runId: string;
  bankItems: number;
  modelCount: number;
  naiveFloor: number;
  /** Paired comparisons decisive after Holm correction, of totalPairs. */
  decisivePairs: number;
  totalPairs: number;
}

export interface ShipSenseTeaserRow {
  label: string;
  score: number;
}

// Mirrors the verdict wording on the canonical board (README generations table).
export const SHIP_SENSE_VERDICT_TEXT: Record<ShipSenseVerdict, string> = {
  "decisive-up": "decisive upgrade",
  "suggestive-up": "slight upgrade — not conclusive after correction",
  up: "slight upgrade — not statistically significant",
  even: "dead even",
  down: "slight downgrade — not statistically significant",
  "suggestive-down": "slight downgrade — not conclusive after correction",
  "decisive-down": "decisive downgrade",
};

const PROVIDER_LABELS: Record<string, string> = {
  anthropic: "Anthropic",
  openai: "OpenAI",
  google: "Google",
  xai: "xAI",
  meta: "Meta",
  moonshot: "Moonshot",
};

export const providerLabel = (provider: string): string =>
  PROVIDER_LABELS[provider] ??
  provider.charAt(0).toUpperCase() + provider.slice(1);

/**
 * Dataset JSON-LD for /benchmark — single source shared by the page's useHead
 * call and scripts/prerender-routes.ts, so the two can't drift.
 */
export const buildShipSenseJsonLd = (run: {
  version: string;
  runId: string;
}): Record<string, unknown> => ({
  "@context": "https://schema.org",
  "@type": "Dataset",
  name: "Ship Sense leaderboard",
  description: SHIP_SENSE_DESCRIPTION,
  url: "https://llmvibes.ai/benchmark",
  sameAs: [SHIP_SENSE_REPO_URL, SHIP_SENSE_BOARD_URL],
  license: "https://opensource.org/licenses/MIT",
  version: run.version,
  dateModified: run.runId,
  isBasedOn: SHIP_SENSE_REPO_URL,
  creator: { "@type": "Person", name: AUTHOR_NAME, sameAs: AUTHOR_SAMEAS },
});

export interface ShipSenseDimension {
  name: string;
  question: string;
  grading: string;
}

// Copy source: ship-sense README "What it measures" table.
export const SHIP_SENSE_DIMENSIONS: ShipSenseDimension[] = [
  {
    name: "Restraint",
    question:
      "What do you refuse to build, and where do you draw an AI agent's autonomy line?",
    grading:
      "SHIP / DEFER / KILL per feature against a documented key; traps weighted 2×; some items add a hard capacity cap.",
  },
  {
    name: "Honesty",
    question: "What can this data, and this model's own output, actually support?",
    grading:
      "Binary checks for documented landmines and enumerated false conclusions, including over-skeptical dismissal.",
  },
  {
    name: "Conviction",
    question: "Hold a call under pressure, and update only on real evidence?",
    grading:
      "Multi-turn: resist social pressure and weak or confident-but-wrong output; update on genuine evidence.",
  },
];
