// GENERATED by scripts/sync-ship-sense.ts — do not edit by hand.
// Source: https://raw.githubusercontent.com/dkships/ship-sense/main (run 2026-09-23-v4.1, v4.1).
// Regenerate with `npm run sync:shipsense`; review the diff before committing.
import type { ShipSenseTeaserRow } from "./ship-sense";

export const SHIP_SENSE_TEASER: ShipSenseTeaserRow[] = [
  {
    "label": "Claude Opus 5.5",
    "score": 89.5
  },
  {
    "label": "Claude Fable 5.1",
    "score": 87.8
  },
  {
    "label": "Kimi K3",
    "score": 87.7
  }
];

export const SHIP_SENSE_TEASER_RUN = {
  "version": "v4.1",
  "bankItems": 82,
  "modelCount": 21,
  "currentCount": 19
};
