// GENERATED by scripts/sync-ship-sense.ts — do not edit by hand.
// Source: https://raw.githubusercontent.com/dkships/ship-sense/main (run 2026-09-22-v4, v4.0).
// Regenerate with `npm run sync:shipsense`; review the diff before committing.
import type { ShipSenseTeaserRow } from "./ship-sense";

export const SHIP_SENSE_TEASER: ShipSenseTeaserRow[] = [
  {
    "label": "Claude Opus 5.5",
    "score": 86.7
  },
  {
    "label": "Kimi K3",
    "score": 86
  },
  {
    "label": "Claude Fable 5.1",
    "score": 84.8
  }
];

export const SHIP_SENSE_TEASER_RUN = {
  "version": "v4.0",
  "bankItems": 78,
  "modelCount": 21,
  "currentCount": 19
};
