// GENERATED by scripts/sync-ship-sense.ts — do not edit by hand.
// Source: https://raw.githubusercontent.com/dkships/ship-sense/main (run 2026-10-06-v4.3, v4.3).
// Regenerate with `npm run sync:shipsense`; review the diff before committing.
import type { ShipSenseTeaserRow } from "./ship-sense";

export const SHIP_SENSE_TEASER: ShipSenseTeaserRow[] = [
  {
    "label": "Claude Opus 5.5",
    "score": 88.4
  },
  {
    "label": "Claude Fable 5.1",
    "score": 87.4
  },
  {
    "label": "Kimi K3",
    "score": 86.8
  }
];

export const SHIP_SENSE_TEASER_RUN = {
  "version": "v4.3",
  "bankItems": 93,
  "modelCount": 24,
  "currentCount": 19
};
